import type { Metadata } from 'next'
import { Inter, Luckiest_Guy } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar';
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const luckiestGuy  = Luckiest_Guy({
  subsets: ['latin'],
  variable: '--font-luckiest-guy',
  weight: '400',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${luckiestGuy.variable}`}>
      <NavBar />
      {children}</body>
    </html>
  )
}
